image: Visual Studio 2019

environment:
  CODACY_PROJECT_TOKEN:
    secure: xprpiCGL823NKrs/K2Cps1UVBEmpezXReLxcfLyU1M43ZBBOK91xvjdIJamYKi8D
  DEPLOY_ONLY: false
  EXTRA_SETUP_ARGS: ""
  matrix:
  - PYTHON: C:\Python36-x64\python.exe
    platform: x64
    EXTRA_SETUP_ARGS: "--py-limited-api cp36"
  - PYTHON: C:\Python36\python.exe
    platform: Any CPU
    EXTRA_SETUP_ARGS: "--py-limited-api cp36"
  - PYTHON: C:\Python37-x64\python.exe
    platform: x64
    NO_DEPLOY: true
  - PYTHON: C:\Python38-x64\python.exe
    platform: x64
    NO_DEPLOY: true
  - PYTHON: C:\Python39-x64\python.exe
    platform: x64
    NO_DEPLOY: true

matrix:
  allow_failures:
    - DEPLOY_ONLY: true
clone_depth: 50

init:
- cmd: "if %APPVEYOR_REPO_TAG%==false if %DEPLOY_ONLY%==true exit /b 1"

install:
- cmd: "git submodule update --init --recursive"
- ps: ". .appveyor/install_python.ps1"
- cmd: "%ACTIVATE_VENV%"
- cmd: "set PATH=%APPVEYOR_BUILD_FOLDER%\\venv\\bin;%PATH%"
- cmd: "set PATH=%PATH%;C:\\MinGW\\bin"
- cmd: "python --version"
- cmd: "python -m pip install --upgrade pip"
- cmd: "pip install --requirement requirements.txt"
- cmd: "python -O setup.py build sdist develop bdist_wheel %EXTRA_SETUP_ARGS%"
build: off
before_test:
- cmd: "pip install pytest pytest-cov"
test_script:
- ps: "pytest -v"

on_success:
- pip install codacy-coverage
- coverage xml
- if defined CODACY_PROJECT_TOKEN python-codacy-coverage -r coverage.xml || cd .
