[build-system]
requires = ["setuptools>=57.0.0", "wheel", "cffi~=1.13", "pycparser>=2.14"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ["py37"]

[tool.isort]
profile = "black"
py_version = "37"
skip_gitignore = true
line_length = 120
