# This makes sure that the latest versions of the SDL headers parse correctly.

name: Parse SDL

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  parse_sdl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-2019", "macos-latest"]
        python-version: ["3.x"]
        sdl-version: ["2.0.14", "2.0.16"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        run: |
          git submodule update --init --recursive --depth 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build package.
        run: |
          python setup.py build
        env:
          SDL_VERSION: ${{ matrix.sdl-version }}
