# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    env:
      python-version: "3.9"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule update --init --recursive --depth 1
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 mypy black isort pytest types-tabulate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Fake initialize package
        run: |
          echo '__version__ = ""' > tcod/version.py
      - name: Flake8
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: flake8 scripts/ tcod/ tests/
      - name: MyPy
        if: always()
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: mypy
          run: mypy --show-column-numbers .
      - name: isort
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: isort
          run: isort scripts/ tcod/ tests/ --check --diff
      - name: isort (examples)
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: isort
          run: isort examples/ --check --diff --thirdparty tcod
      - name: Black
        run: |
          black --check --diff examples/ scripts/ tcod/ tests/ *.py
